#!/bin/bash

yes | yum update

yes | yum install epel-release

yes | yum install nodejs

yum install gcc-c++ make

npm cache clean -f

npm install -g n

n stable

> /etc/yum.repos.d/grafana.repo

echo -e "[grafana] \nname=grafana \nbaseurl=https://packages.grafana.com/oss/rpm \nrepo_gpgcheck=1 \nenabled=1 \ngpgcheck=1 \ngpgkey=https://packages.grafana.com/gpg.key \nsslverify=1 \nsslcacert=/etc/pki/tls/certs/ca-bundle.crt" > /etc/yum.repos.d/grafana.repo

yes | yum update

yes | yum install grafana

systemctl start grafana-server
systemctl enable grafana-server

#helm
grafana-cli plugins install opennms-helm-app
systemctl restart grafana-server
############


